function Hd = BandstopFilter2
%BANDSTOPFILTER2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 29-Dec-2024 18:27:32

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

N      = 150;   % Order
Fpass1 = 1000;  % First Passband Frequency
Fstop1 = 1500;  % First Stopband Frequency
Fstop2 = 3000;  % Second Stopband Frequency
Fpass2 = 4000;  % Second Passband Frequency
Wpass1 = 0.1;   % First Passband Weight
Wstop  = 40;    % Stopband Weight
Wpass2 = 0.1;   % Second Passband Weight
dens   = 20;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass1 Fstop1 Fstop2 Fpass2 Fs/2]/(Fs/2), [1 1 0 0 1 ...
           1], [Wpass1 Wstop Wpass2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
